### ISSUE TITLE
CoreOS google-clock-sync-manager.service failure

### ISSUE THREAD

**Issue by cmoad** [coreos/bugs#1468]
# Issue Report #

## Bug ##

google-clock-sync-manager.service fails periodically for new instance creation and reboots on GCE.

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1068.8.0
VERSION_ID=1068.8.0
BUILD_ID=2016-07-18-0616
PRETTY_NAME="CoreOS 1068.8.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

These are stable instances running on Google Compute Engine. It sounds like Google might have a fix for this already (https://github.com/GoogleCloudPlatform/compute-image-packages/issues/304).

### Reproduction Steps ###

  1. Start new instance in GCE using latest CoreOS stable (1068.8.0).
  2. `journalctl -u google-clock-sync-manager.service`
```
-- Logs begin at Tue 2016-07-19 14:39:17 UTC, end at Wed 2016-07-20 15:52:56 UTC. --
Jul 19 14:39:27 localhost systemd[1]: Started Google Compute Engine Clock Sync Daemon.
Jul 19 14:39:27 k8s-node-backend01.c.geofeedia-qa1.internal google-clock-sync[1102]: INFO Starting GCE clock sync
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]: Traceback (most recent call last):
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/google-compute-daemon/manage_clock_sync.py", line 85, in <module>
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     Main()
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/google-compute-daemon/manage_clock_sync.py", line 81, in Main
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     lock_file.RunExclusively(lock_fname, HandleClockDriftToken(watcher, OnChange))
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/google-compute-daemon/manage_clock_sync.py", line 51, in HandleClockDriftToken
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     Handler, initial_value='')
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/google-compute-daemon/metadata_watcher.py", line 74, in WatchMetadataForever
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     response = self.urllib2.urlopen(req)
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/python/lib64/python2.7/urllib2.py", line 127, in urlopen
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     return _opener.open(url, data, timeout)
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/python/lib64/python2.7/urllib2.py", line 404, in open
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     response = self._open(req, data)
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/python/lib64/python2.7/urllib2.py", line 422, in _open
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     '_open', req)
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/python/lib64/python2.7/urllib2.py", line 382, in _call_chain
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     result = func(*args)
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/python/lib64/python2.7/urllib2.py", line 1214, in http_open
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     return self.do_open(httplib.HTTPConnection, req)
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/python/lib64/python2.7/urllib2.py", line 1187, in do_open
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     r = h.getresponse(buffering=True)
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/python/lib64/python2.7/httplib.py", line 1045, in getresponse
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     response.begin()
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/python/lib64/python2.7/httplib.py", line 409, in begin
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     version, status, reason = self._read_status()
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/python/lib64/python2.7/httplib.py", line 365, in _read_status
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     line = self.fp.readline(_MAXLINE + 1)
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:   File "/usr/share/oem/python/lib64/python2.7/socket.py", line 476, in readline
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]:     data = self._sock.recv(self._rbufsize)
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal python2.7[1102]: socket.error: [Errno 104] Connection reset by peer
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal systemd[1]: google-clock-sync-manager.service: Main process exited, code=exited, status=1/FAILURE
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal systemd[1]: google-clock-sync-manager.service: Unit entered failed state.
Jul 19 15:39:27 k8s-node-backend01.c.geofeedia-qa1.internal systemd[1]: google-clock-sync-manager.service: Failed with result 'exit-code'.
```

**Comment by crawford** [comment]
This failure shouldn't affect normal operation of the machine. As far as I understand, this utility is mostly useful for shapshots or migrating machines. That being said, we are working on getting the latest GCE tools into a rkt image.

**Comment by JacobHayes** [comment]
I know this issue has been closed for quite a while, but we're still seeing this issue on our instances (version: 1520.6.0). Do the instances need to be deleted and recreated to get these fixes?

**Comment by euank** [comment]
@JacobHayes unfortunately, yes. The OEM partition doesn't get updated automatically for rather unfortunate historical reasons.

Reprovisioning should pick up the changes. If it doesn't, please do file a bug
