### ISSUE TITLE
rkt-gc 1.21 panic

### ISSUE THREAD

**Issue by dghubble** [coreos/bugs#1943]
# Issue Report #

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.7.0
VERSION_ID=1298.7.0
BUILD_ID=2017-03-31-0215
PRETTY_NAME="Container Linux by CoreOS 1298.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### rkt version

```
rkt Version: 1.21.0
appc Version: 0.8.9
Go Version: go1.7.3
Go OS/Arch: linux/amd64
Features: -TPM +SDJOURNAL
```

### Environment ###

Hardware

### Actual Behavior ###

bootkube v0.4.1 controller node was left running for about 24 hours. The rkt-gc.service failed some time during that period. Restarting resolved the issue.

```
Starting Garbage Collection for rkt...
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: gc: moving pod "8cae75b9-fc8a-432b-9c37-1353661f53cf" to garbage
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: gc: moving pod "b1fb0266-95b8-470b-80d6-9f3460427857" to garbage
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: Garbage collecting pod "6a3c97c5-ff52-47d1-acc0-6c909f54b49b"
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: gc: pod "8cae75b9-fc8a-432b-9c37-1353661f53cf" not removed: still within grace period (24h0m0s)
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5fb096]
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: goroutine 1 [running, locked to thread]:
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: panic(0xc00080, 0xc420012050)
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]:         /usr/lib/go1.7/src/runtime/panic.go:500 +0x1a1
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: github.com/coreos/rkt/pkg/lock.(*FileLock).TrySharedLock(0x0, 0xc420175250, 0x129d080)
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]:         /build/amd64-usr/var/tmp/portage/app-emulation/rkt-1.21.0/work/rkt-1.21.0/build-rkt-1.21.0/gopath/src/github.com/coreos/rkt/pkg/lock/file.go:96
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: github.com/coreos/rkt/pkg/pod.getPod(0xc42015f330, 0xc, 0xc420476da0, 0x0, 0x0, 0x0)
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]:         /build/amd64-usr/var/tmp/portage/app-emulation/rkt-1.21.0/work/rkt-1.21.0/build-rkt-1.21.0/gopath/src/github.com/coreos/rkt/pkg/pod/pods.go:233
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: github.com/coreos/rkt/pkg/pod.WalkPods(0xc42015f330, 0xc, 0xc42015f310, 0xc4204d9ba8, 0x0, 0x0)
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]:         /build/amd64-usr/var/tmp/portage/app-emulation/rkt-1.21.0/work/rkt-1.21.0/build-rkt-1.21.0/gopath/src/github.com/coreos/rkt/pkg/pod/pods.go:914
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: main.emptyExitedGarbage(0x4e94914f0000, 0x0, 0x0)
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]:         /build/amd64-usr/var/tmp/portage/app-emulation/rkt-1.21.0/work/rkt-1.21.0/build-rkt-1.21.0/gopath/src/github.com/coreos/rkt/rkt/gc.go:138 +0x62
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: main.runGC(0x1290800, 0xc42015f230, 0x0, 0x1, 0x51e522)
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]:         /build/amd64-usr/var/tmp/portage/app-emulation/rkt-1.21.0/work/rkt-1.21.0/build-rkt-1.21.0/gopath/src/github.com/coreos/rkt/rkt/gc.go:87 +0x10d
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: main.runWrapper.func1(0x1290800, 0xc42015f230, 0x0, 0x1)
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]:         /build/amd64-usr/var/tmp/portage/app-emulation/rkt-1.21.0/work/rkt-1.21.0/build-rkt-1.21.0/gopath/src/github.com/coreos/rkt/rkt/rkt.go:242 +0xe
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: main.ensureSuperuser.func1(0x1290800, 0xc42015f230, 0x0, 0x1)
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]:         /build/amd64-usr/var/tmp/portage/app-emulation/rkt-1.21.0/work/rkt-1.21.0/build-rkt-1.21.0/gopath/src/github.com/coreos/rkt/rkt/rkt.go:256 +0x1
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: github.com/coreos/rkt/vendor/github.com/spf13/cobra.(*Command).execute(0x1290800, 0xc42015f210, 0x1, 0x1, 0x1290800, 0xc42015f210)
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]:         /build/amd64-usr/var/tmp/portage/app-emulation/rkt-1.21.0/work/rkt-1.21.0/build-rkt-1.21.0/gopath/src/github.com/coreos/rkt/vendor/github.com/s
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: github.com/coreos/rkt/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x128e800, 0x0, 0x0, 0x0)
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]:         /build/amd64-usr/var/tmp/portage/app-emulation/rkt-1.21.0/work/rkt-1.21.0/build-rkt-1.21.0/gopath/src/github.com/coreos/rkt/vendor/github.com/s
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: github.com/coreos/rkt/vendor/github.com/spf13/cobra.(*Command).Execute(0x128e800, 0xcd1c56, 0xc4200001a0)
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]:         /build/amd64-usr/var/tmp/portage/app-emulation/rkt-1.21.0/work/rkt-1.21.0/build-rkt-1.21.0/gopath/src/github.com/coreos/rkt/vendor/github.com/s
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]: main.main()
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io rkt[1212]:         /build/amd64-usr/var/tmp/portage/app-emulation/rkt-1.21.0/work/rkt-1.21.0/build-rkt-1.21.0/gopath/src/github.com/coreos/rkt/rkt/main.go:32 +0x9
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io systemd[1]: rkt-gc.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 28 20:50:29 sm-x8dtu0.us-west1-m.dghubble.io systemd[1]: Failed to start Garbage Collection for rkt.
```

**Comment by dghubble** [comment]
Similar to https://github.com/rkt/rkt/issues/3513

**Comment by euank** [comment]
Should be fixed in the current stable
