### ISSUE TITLE
Shutdown scripts fail to get metadata in GCE

### ISSUE THREAD

**Issue by matti** [coreos/bugs#1999]
Prob. due to network is killed before the script has completed..?
```
Jun 12 11:56:03 instance-1.c.myproject.internal systemd[1]: Stopping GCE Linux Agent...
Jun 12 11:56:03 instance-1.c.myproject.internal shutdown-script[987]: INFO Starting shutdown scripts.
Jun 12 11:56:03 instance-1.c.myproject.internal shutdown-script[987]: ERROR GET request error retrieving metadata.
                                                                     Traceback (most recent call last):
                                                                       File "/usr/lib64/python2.7/site-packages/google_compute_engine/metadata_watcher.py", line 170, in _HandleMetadataUpdate
                                                                         timeout=timeout)
                                                                       File "/usr/lib64/python2.7/site-packages/google_compute_engine/metadata_watcher.py", line 139, in _GetMetadataUpdate
                                                                         metadata_url, params=params, timeout=timeout)
                                                                       File "/usr/lib64/python2.7/site-packages/google_compute_engine/metadata_watcher.py", line 50, in Wrapper
                                                                         response = func(*args, **kwargs)
                                                                       File "/usr/lib64/python2.7/site-packages/google_compute_engine/metadata_watcher.py", line 99, in _GetMetadataRequest
                                                                         return request_opener.open(request, timeout=timeout*1.1)
                                                                       File "/usr/lib64/python2.7/urllib2.py", line 429, in open
                                                                         response = self._open(req, data)
                                                                       File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
                                                                         '_open', req)
                                                                       File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
                                                                         result = func(*args)
                                                                       File "/usr/lib64/python2.7/urllib2.py", line 1228, in http_open
                                                                         return self.do_open(httplib.HTTPConnection, req)
                                                                       File "/usr/lib64/python2.7/urllib2.py", line 1198, in do_open
                                                                         raise URLError(err)
                                                                     URLError: <urlopen error [Errno -2] Name or service not known>
Jun 12 11:57:33 instance-1.c.myproject.internal systemd[1]: oem-gce.service: State 'stop-sigterm' timed out. Killing.
Jun 12 11:57:33 instance-1.c.myproject.internal systemd[1]: oem-gce.service: Killing process 987 (google_metadata) with signal SIGKILL.
Jun 12 11:57:33 instance-1.c.myproject.internal systemd[1]: oem-gce.service: Main process exited, code=killed, status=9/KILL
Jun 12 11:57:33 instance-1.c.myproject.internal rkt[1273]: gc: moving pod "78f99e3c-2575-4975-ab65-4da589ffe997" to garbage
Jun 12 11:57:33 instance-1.c.myproject.internal systemd[1]: Stopped GCE Linux Agent.
Jun 12 11:57:33 instance-1.c.myproject.internal systemd[1]: oem-gce.service: Unit entered failed state.
Jun 12 11:57:33 instance-1.c.myproject.internal systemd[1]: oem-gce.service: Failed with result 'timeout'.
-- Reboot --
```

ping https://github.com/coreos/bugs/issues/1746

**Comment by matti** [comment]
NOTE: this might have to do something with my setup where I'm running weave.

**Comment by euank** [comment]
Since `oem-gce.service` is `After=network-online.target`, that means it should be taken down before the network is.

Can you also provide the usual additional information?
Namely Container Linux version, what the original version was (so we can know which oem partition version it has), and the additional network configuration you mention.

**Comment by Constantin07** [comment]
We are experiencing a similar issue.

```
[Unit]
Description=Events
DefaultDependencies=no
Wants=network-online.target
Wants=nss-lookup.target
After=network.target
After=network-online.target
After=nss-lookup.target

[Service]
ExecStart=/usr/bin/curl -XPOST -d "event=startup" https://requestb.in/1nrqfy21
ExecStop=/usr/bin/curl -XPOST -d "event=shutdown" https://requestb.in/1nrqfy21

Type=oneshot
RemainAfterExit=yes
TimeoutSec=2min

[Install]
WantedBy=multi-user.target
```

We see it push out "startup" events but never a "shutdown" event on shutdown, halt, reboot, initiated shutdown via ACPI.

You can take a look at the storage here: https://requestb.in/1nrqfy21?inspect

For easier reproducibility here is the CoreOS ignition config that we're using against the latest stable branch of CoreOS on AWS:

{"ignition":{"version":"2.0.0","config":{}},"storage":{},"systemd":{"units":[{"name":"event-notification.service","enable":true,"contents":"[Unit]\nDescription=Events\nDefaultDependencies=no\nWants=network-online.target\nWants=nss-lookup.target\nAfter=network.target\nAfter=network-online.target\nAfter=nss-lookup.target\n\n[Service]\nExecStart=/usr/bin/curl -XPOST -d \"event=startup\" https://requestb.in/1nrqfy21\nExecStop=/usr/bin/curl -XPOST -d \"event=shutdown\" https://requestb.in/1nrqfy21\n\nType=oneshot\nRemainAfterExit=yes\nTimeoutSec=2min\n\n[Install]\nWantedBy=multi-user.target\n"}]},"networkd":{},"passwd":{}}

It works fine on Debian Linux. Looks like it's broken in CoreOS probably in the way networking is done.

**Comment by crawford** [comment]
@Constantin07 I was able to repro your report on the latest Alpha (1520.0.0). Interestingly, the ExecStop isn't executed at all (I modified your service to also touch a file). If I manually stop the service, everything works as intended. I haven't dug into why systemd isn't running the ExecStop.
