### ISSUE TITLE
Mayday crashes when gathering docker info

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#2077]
# Issue Report #

### Container Linux Version ###

1409.5.0

### Other Information ###

```
panic: interface conversion: interface is nil, not []interface {}
goroutine 1 [running]:
panic(0x8c0ae0, 0xc4213ab100)
    /usr/lib/go1.7/src/runtime/panic.go:500 +0x1a1
github.com/coreos/mayday/mayday/plugins/docker.(*DockerContainer).Content(0xc420775580, 0xc421c722a0)
    /build/amd64-usr/var/tmp/portage/app-admin/mayday-1.0.0/work/gopath/src/github.com/coreos/mayday/mayday/plugins/docker/docker.go:55 +0x23c
github.com/coreos/mayday/mayday/plugins/docker.(*DockerContainer).Header(0xc420775580, 0xc420757200)
    /build/amd64-usr/var/tmp/portage/app-admin/mayday-1.0.0/work/gopath/src/github.com/coreos/mayday/mayday/plugins/docker/docker.go:75 +0x15b
github.com/coreos/mayday/mayday/tar.(*Tar).Add(0xc42043db28, 0xb95880, 0xc420775580, 0xc42062625b, 0x40)
    /build/amd64-usr/var/tmp/portage/app-admin/mayday-1.0.0/work/gopath/src/github.com/coreos/mayday/mayday/tar/tar.go:31 +0x49
github.com/coreos/mayday/mayday.Run(0xc420448000, 0xc420757200, 0xc420442880, 0x16, 0xc420670000, 0x264, 0x400, 0x9428a3, 0x1)
    /build/amd64-usr/var/tmp/portage/app-admin/mayday-1.0.0/work/gopath/src/github.com/coreos/mayday/mayday/mayday.go:11 +0x6f
main.main()
    /build/amd64-usr/var/tmp/portage/app-admin/mayday-1.0.0/work/gopath/src/github.com/coreos/mayday/mayday.go:199 +0x1426
```

This corresponds to [this line](https://github.com/coreos/mayday/blob/168950551e751ed40ef94249d638b7e6547eacfc/mayday/plugins/docker/docker.go#L55) which is a terrifying line of code.

**Comment by euank** [comment]
Thanks github. That's not what I wanted. Anyways, PR over here https://github.com/coreos/mayday/pull/70
