### ISSUE TITLE
Excessive bioset threads and Docker resource allocation failures

### ISSUE THREAD

**Issue by patrick-east** [coreos/bugs#2167]
# Issue Report #

## Bug ##

Systems with heavy docker volume usage utilizing iSCSI block devices seem to be accumulating `bioset` threads. Eventually when the number is high enough Docker starts to have failures like saying: "pthread_create failed: Resource temporarily unavailable" which is presumably because there are close to 50k bioset process/threads running...

### Container Linux Version ###

```
patrick-coreos-1 ~ # cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1465.8.0
VERSION_ID=1465.8.0
BUILD_ID=2017-09-20-2237
PRETTY_NAME="Container Linux by CoreOS 1465.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

KVM hypervisor with OpenStack on Intel HW:
```
patrick-coreos-1 ~ # uname -a
Linux patrick-coreos-1.novalocal 4.12.14-coreos #1 SMP Wed Sep 20 22:20:05 UTC 2017 x86_64 Intel Xeon E3-12xx v2 (Ivy Bridge) GenuineIntel GNU/Linux
```

### Expected Behavior ###

When removing iSCSI block devices the bioset threads should be cleaned up.

### Actual Behavior ###

The threads seem to be getting leaked... or something related to them is leaking. Every time a volume is attached and then detached we leave behind >1 bioset threads. Eventually a system gets to 48,000+ (judging by a ps aux | grep bioset | wc -l) and gets failures to allocate new pthreads. The end-user impact being we see errors like:

(formatting is kind of gross in the log, but the gist is there)
```
/run/torcx/bin/docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 2, stdout: , stderr: runtime/cgo: pthread_create failed: Resource temporarily unavailable\\\\nruntime/cgo: pthread_create failed: Resource temporarily unavailable\\\\nSIGABRT: abort\\\\nPC=0x7fed8e407f47 m=0\\\\n\\\\ngoroutine 0 [idle]:\\\\n\\\\ngoroutine 1 [chan receive, locked to thread]:\\\\nruntime.gopark(0x18033b0, 0xc420078058, 0x1708e5b, 0xc, 0x17, 0x3)\\\\n\\\\t/usr/lib/go1.7/src/runtime/proc.go:259 +0x13a\\\\nruntime.goparkunlock(0xc420078058, 0x1708e5b, 0xc, 0xc42006de17, 0x3)\\\\n\\\\t/usr/lib/go1.7/src/runtime/proc.go:265 +0x5e\\\\nruntime.chanrecv(0x14726e0, 0xc420078000, 0x0, 0xc42006df01, 0x42a0c1)\\\\n\\\\t/usr/lib/go1.7/src/runtime/chan.go:496 +0x2df\\\\nruntime.chanrecv1(0x14726e0, 0xc420078000, 0x0)\\\\n\\\\t/usr/lib/go1.7/src/runtime/chan.go:378 +0x35\\\\nruntime.gcenable()\\\\n\\\\t/usr/lib/go1.7/src/runtime/mgc.go:196 +0x84\\\\nruntime.main()\\\\n\\\\t/usr/lib/go1.7/src/runtime/proc.go:151 +0x12a\\\\nruntime.goexit()\\\\n\\\\t/usr/lib/go1.7/src/runtime/asm_amd64.s:2086 +0x1\\\\n\\\\ngoroutine 17 [syscall, locked to thread]:\\\\nruntime.goexit()\\\\n\\\\t/usr/lib/go1.7/src/runtime/asm_amd64.s:2086 +0x1\\\\n\\\\nrax    0x0\\\\nrbx    0x7fed8e7787a0\\\\nrcx    0x7fed8e407f47\\\\nrdx    0x6\\\\nrdi    0x7c36\\\\nrsi    0x7c36\\\\nrbp    0x184576a\\\\nrsp    0x7ffd8fb50688\\\\nr8     0x7fed8e7798e0\\\\nr9     0x7fed8f4f3880\\\\nr10    0x8\\\\nr11    0x206\\\\nr12    0x257c070\\\\nr13    0xf3\\\\nr14    0x30\\\\nr15    0x3\\\\nrip    0x7fed8e407f47\\\\nrflags 0x206\\\\ncs     0x33\\\\nfs     0x0\\\\ngs     0x0\\\\n\\\"\"\n".
11:31:08 		
```

### Reproduction Steps ###

  1. Attach an iSCSI block device 
  2. Delete the SCSI device associated with the iSCSI LUN (ex: sda)
  3. Close iSCSI session and delete node
  4. bioset thread remains

### Other Information ###

Example below showing it, keep an eye on `[bioset]` with PID 852

```
# Host 10.231.128.25 found: line 104
/home/patrick/.ssh/known_hosts updated.
Original contents retained as /home/patrick/.ssh/known_hosts.old
Warning: Permanently added '10.231.128.25' (ECDSA) to the list of known hosts.
Last login: Mon Sep 25 21:24:35 UTC 2017 from 10.206.99.46 on pts/1
Container Linux by CoreOS stable (1465.8.0)
patrick-coreos-1 ~ # ps aux | grep bioset
root        42  0.0  0.0      0     0 ?        S<   21:26   0:00 [bioset]
root        47  0.0  0.0      0     0 ?        S<   21:26   0:00 [bioset]
root       341  0.0  0.0      0     0 ?        S<   21:26   0:00 [bioset]
root       794  0.0  0.0   6736   864 pts/0    S+   21:26   0:00 grep --colour=auto bioset
patrick-coreos-1 ~ # iscsiadm -m node
iscsiadm: No records found
patrick-coreos-1 ~ #  iscsiadm -m node --op new -T iqn.2010-06.com.purestorage:flasharray.3adbe40b49bac873 -p 10.0.5.11:3260
New iSCSI node [tcp:[hw=,ip=,net_if=,iscsi_if=default] 10.0.5.11,3260,-1 iqn.2010-06.com.purestorage:flasharray.3adbe40b49bac873] added
patrick-coreos-1 ~ #  iscsiadm -m node -T iqn.2010-06.com.purestorage:flasharray.3adbe40b49bac873 -p 10.0.5.11:3260 --login
Logging in to [iface: default, target: iqn.2010-06.com.purestorage:flasharray.3adbe40b49bac873, portal: 10.0.5.11,3260] (multiple)
Login to [iface: default, target: iqn.2010-06.com.purestorage:flasharray.3adbe40b49bac873, portal: 10.0.5.11,3260] successful.
patrick-coreos-1 ~ # ls /dev | grep sd
sda
patrick-coreos-1 ~ # ps aux | grep bioset
root        42  0.0  0.0      0     0 ?        S<   21:26   0:00 [bioset]
root        47  0.0  0.0      0     0 ?        S<   21:26   0:00 [bioset]
root       341  0.0  0.0      0     0 ?        S<   21:26   0:00 [bioset]
root       852  0.0  0.0      0     0 ?        S<   21:28   0:00 [bioset]
root       862  0.0  0.0   6736   892 pts/0    S+   21:29   0:00 grep --colour=auto bioset
patrick-coreos-1 ~ # echo 1 > /sys/block/sda/device/delete
patrick-coreos-1 ~ # ps aux | grep bioset
root        42  0.0  0.0      0     0 ?        S<   21:26   0:00 [bioset]
root        47  0.0  0.0      0     0 ?        S<   21:26   0:00 [bioset]
root       341  0.0  0.0      0     0 ?        S<   21:26   0:00 [bioset]
root       852  0.0  0.0      0     0 ?        S<   21:28   0:00 [bioset]
root       870  0.0  0.0   6736   920 pts/0    S+   21:29   0:00 grep --colour=auto bioset
patrick-coreos-1 ~ # iscsiadm -m session --logout all
Logging out of session [sid: 1, target: iqn.2010-06.com.purestorage:flasharray.3adbe40b49bac873, portal: 10.0.5.11,3260]
Logout of [sid: 1, target: iqn.2010-06.com.purestorage:flasharray.3adbe40b49bac873, portal: 10.0.5.11,3260] successful.
patrick-coreos-1 ~ # iscsiadm -m node --op delete all
patrick-coreos-1 ~ # ps aux | grep bioset
root        42  0.0  0.0      0     0 ?        S<   21:26   0:00 [bioset]
root        47  0.0  0.0      0     0 ?        S<   21:26   0:00 [bioset]
root       341  0.0  0.0      0     0 ?        S<   21:26   0:00 [bioset]
root       852  0.0  0.0      0     0 ?        S<   21:28   0:00 [bioset]
root       879  0.0  0.0   6736   912 pts/0    S+   21:29   0:00 grep --colour=auto bioset
patrick-coreos-1 ~ # ls /dev | grep sd
patrick-coreos-1 ~ #
```

I tested this out with an older CoreOS image I had (1185.5.0) and this doesn't reproduce, but on the newer stable version (1486.8.0) it is 100% reproducible.

**Comment by patrick-east** [comment]
FWIW, tested this out on the beta channel and things are looking wayy better. I saw some changes in the 4.13 kernel that were related... might have been fixed with that version bump.

**Comment by bgilbert** [comment]
@patrick-east Sounds good, please keep us informed.  4.13 should reach stable in a couple weeks.

**Comment by r7vme** [comment]
We also experience similar problem. We have three master nodes (CoreOS 1409.7.0) with iscsi volumes attached by Kubernetes and they keep rebooting once in 1-2 days. Nodes w/o iscsi are totally fine.

In log usually nothing, but once kernel was able to log
```
Dec 06 04:43:02 0000b0112d294c69 kernel: BUG: unable to handle kernel NULL pointer dereference at 0000000000000078
Dec 06 04:43:02 0000b0112d294c69 kernel: IP: iscsi_requeue_task+0x169/0x950 [libiscsi]
```

I potentially similar [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1451233) here also.

**Comment by r7vme** [comment]
We've upgraded nodes to latest Stable verision 1576.4.0, which has kernel 4.13, but this did not help. Node with iscsi keeps rebooting.

```
Linux 000083333c033937 4.13.16-coreos-r2 #1 SMP Wed Dec 6 04:27:34 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz GenuineIntel GNU/Linux
```

**Comment by r7vme** [comment]
Interesting patch [1] that can be related to our issue.

1 - https://groups.google.com/forum/#!topic/open-iscsi/-HOsGZ_GT9I
