### ISSUE TITLE
/usr/bin/emerge-gitclone raises exception OSError: [Errno 38] Function not implemented

### ISSUE THREAD

**Issue by squat** [coreos/bugs#2414]
# Issue Report #

## Bug ##
Starting with the Beta 1745.1.0 developer container, running `/usr/bin/emerge-gitclone` causes python to raise the exception.
### Container Linux Version ###
Beta 1745.1.0

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.1.0
VERSION_ID=1745.1.0
BUILD_ID=2018-04-24-0719
PRETTY_NAME="Container Linux by CoreOS 1745.1.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###
What hardware/cloud provider/hypervisor is being used to run Container Linux?
Developer container.

### Expected Behavior ###
`/usr/bin/emerge-gitclone` should not fail.
### Actual Behavior ###
The following traceback is generated:
```python
>>> Failed to read manifest commits for 1745.1.0
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/emerge-gitclone", line 37, in <module>
    eroot = portage.settings['EROOT']
  File "/usr/lib64/python2.7/site-packages/portage/proxy/objectproxy.py", line 44, in __getitem__
    return object.__getattribute__(self, '_get_target')()[key]
  File "/usr/lib64/python2.7/site-packages/portage/__init__.py", line 695, in _get_target
    return _get_legacy_global(name)
  File "/usr/lib64/python2.7/site-packages/portage/_legacy_globals.py", line 35, in _get_legacy_global
    portage.db = portage.create_trees(**kwargs)
  File "/usr/lib64/python2.7/site-packages/portage/__init__.py", line 585, in create_trees
    env=env, eprefix=eprefix)
  File "/usr/lib64/python2.7/site-packages/portage/proxy/objectproxy.py", line 30, in __call__
    result = object.__getattribute__(self, '_get_target')()
  File "/usr/lib64/python2.7/site-packages/portage/proxy/lazyimport.py", line 130, in _get_target
    __import__(name)
  File "/usr/lib64/python2.7/site-packages/portage/package/ebuild/config.py", line 39, in <module>
    from portage.dbapi.porttree import portdbapi
  File "/usr/lib64/python2.7/site-packages/portage/dbapi/porttree.py", line 88, in <module>
    portage.process.atexit_register(close_portdbapi_caches)
  File "/usr/lib64/python2.7/site-packages/portage/proxy/objectproxy.py", line 22, in __getattribute__
    result = object.__getattribute__(self, '_get_target')()
  File "/usr/lib64/python2.7/site-packages/portage/proxy/lazyimport.py", line 107, in _get_target
    __import__(name)
  File "/usr/lib64/python2.7/site-packages/portage/process.py", line 27, in <module>
    from portage.util._ctypes import find_library, LoadLibrary, ctypes
  File "/usr/lib64/python2.7/site-packages/portage/util/_ctypes.py", line 6, in <module>
    import ctypes.util
  File "/usr/lib64/python2.7/ctypes/util.py", line 86, in <module>
    import re, tempfile, errno
  File "/usr/lib64/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/usr/lib64/python2.7/random.py", line 885, in <module>
    _inst = Random()
  File "/usr/lib64/python2.7/random.py", line 97, in __init__
    self.seed(x)
  File "/usr/lib64/python2.7/random.py", line 113, in seed
    a = long(_hexlify(_urandom(2500)), 16)
OSError: [Errno 38] Function not implemented
```
### Reproduction Steps ###

  1. Download Beta 1745.1.0 developer container
  2. Run `/usr/bin/emerge-gitclone`

### Other Information ###
I tested and the Beta 1722.2.0 developer container works just fine.

**Comment by dm0-** [comment]
Its test passed during the release build, and I am not able to reproduce a failure locally:

```
beta ~ # emerge-gitclone 
>>> Cloning repository 'portage-stable' from 'https://github.com/coreos/portage-stable.git'...
>>> Starting git clone in /var/lib/portage/portage-stable
Cloning into '/var/lib/portage/portage-stable'...
remote: Counting objects: 86745, done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 86745 (delta 34), reused 42 (delta 22), pack-reused 86676
Receiving objects: 100% (86745/86745), 50.22 MiB | 17.92 MiB/s, done.
Resolving deltas: 100% (44376/44376), done.
>>> Git clone in /var/lib/portage/portage-stable successful
Note: checking out '7f1949e0aaf30977e5d5c0b271cea69047a96406'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 7f1949e0a... Merge pull request #655 from dm0-/glsa
>>> Release checkout 7f1949e0aaf30977e5d5c0b271cea69047a96406 in /var/lib/portage/portage-stable successful
>>> Cloning repository 'coreos' from 'https://github.com/coreos/coreos-overlay.git'...
>>> Starting git clone in /var/lib/portage/coreos-overlay
Cloning into '/var/lib/portage/coreos-overlay'...
remote: Counting objects: 45139, done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 45139 (delta 84), reused 141 (delta 70), pack-reused 44947
Receiving objects: 100% (45139/45139), 14.25 MiB | 17.24 MiB/s, done.
Resolving deltas: 100% (23093/23093), done.
>>> Git clone in /var/lib/portage/coreos-overlay successful
Note: checking out '669b3367521f1183ac7e10829eaeeaa71f539b55'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 669b3367... Merge pull request #3188 from dm0-/build-1745
>>> Release checkout 669b3367521f1183ac7e10829eaeeaa71f539b55 in /var/lib/portage/coreos-overlay successful

Performing Global Updates
(Could take a couple of minutes if you have a lot of binary packages.)


beta ~ # echo $?
0
beta ~ # cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.1.0
VERSION_ID=1745.1.0
BUILD_ID=2018-04-24-0719
PRETTY_NAME="Container Linux by CoreOS 1745.1.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

Does your container have a `/dev/urandom` device node?  Can you run `python -c 'from os import urandom; print(urandom(2500))'`?

**Comment by dm0-** [comment]
Alpha (1772.0.0) now has Python 2.7.14.

**Comment by squat** [comment]
I just ran some tests and can confirm that python and emerge-gitclone is once again working in the Alpha developer container, as expected! Thanks for the help, @dm0-
