### ISSUE TITLE
Is possible to run gdb in a go running process?

### ISSUE THREAD

**Issue by aledbf** [coreos/bugs#316]
I had a problem with docker (memory leak) and I tried to get gdb (inside a container) to get information about the goroutines from the main docker process but it was impossible to load `runtime-gdb.py`

This is some of the output:

```
root@nodo-3:~# gdb docker 774
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from docker...(no debugging symbols found)...done.
Attaching to program: /root/docker, process 774

warning: .dynamic section for "/lib64/ld-linux-x86-64.so.2" is not at the expected address (wrong library or version mismatch?)

warning: Could not load shared library symbols for 11 libraries, e.g. /lib64/libpthread.so.0.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/ld-2.19.so...done.
done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
0x00000000005c118a in syscall.Syscall6 ()
(gdb) info sharedlibrary
From                To                  Syms Read   Shared Object Library
                                        No          linux-vdso.so.1
                                        No          /lib64/libpthread.so.0
                                        No          /lib64/libsqlite3.so.0
                                        No          /lib64/libdevmapper.so.1.02
                                        No          /lib64/libc.so.6
0x00007f10033cfa80  0x00007f10033e8110  Yes         /lib64/ld-linux-x86-64.so.2
                                        No          /lib64/libdl.so.2
                                        No          /lib64/libudev.so.1
                                        No          /lib64/librt.so.1
                                        No          /lib64/libnss_files.so.2
                                        No          /lib64/libnss_usrfiles.so.2
                                        No          /lib64/libnss_dns.so.2
                                        No          /lib64/libresolv.so.2
(gdb) quit
```

```
root@020a28ea4069:/go# gdb -nx -q --batch -ex "source /usr/src/go/src/runtime/runtime-gdb.py" 774
774: No such file or directory.
Loading Go Runtime support.
Traceback (most recent call last):
  File "/usr/src/go/src/runtime/runtime-gdb.py", line 27, in <module>
    goobjfile = gdb.current_objfile() or gdb.objfiles()[0]
IndexError: list index out of range
```

or this one

Traceback (most recent call last):
  File "/usr/src/go/src/runtime/runtime-gdb.py", line 205, in <module>
    _rctp_type = gdb.lookup_type("struct runtime.rtype").pointer()
gdb.error: No struct type named runtime.rtype.

Is possible to do this kind of thing without using https://github.com/coreos/scripts (I don't know if with that is even possible to do what I want)?

**Comment by mischief** [comment]
if you just want the goroutine stacks, one easy way is to send `SIGQUIT` to the process. otherwise, http://godoc.org/net/http/pprof is good for various types of profiling, and can export the current goroutine stacks over http without killing the process (which `SIGQUIT` will do).

**Comment by aledbf** [comment]
almost there https://gist.github.com/aledbf/16d3abceda99d6d09674

**Comment by crawford** [comment]
@aledbf I know it's been a while... but do you still need help with this?

**Comment by crawford** [comment]
Closing due to inactivity.
