### ISSUE TITLE
Push to private registry fails with slice bounds out of range on CoreOS

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#538]
<a href="https://github.com/sdwr98"><img src="https://avatars.githubusercontent.com/u/2473721?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sdwr98](https://github.com/sdwr98)**
_Tuesday Dec 17, 2013 at 15:14 GMT_
_Originally opened as https://github.com/coreos/coreos-overlay/issues/281_

----

Using docker 0.7.1 on CoreOS, I'm trying to push an image to a private registry.  This push worked under docker 0.6.7, but fails on 0.7.1. 

The Dockerfile is really simple:

```
FROM stackbrew/hipache

MAINTAINER Scott Rankin, srankin@crsinc.com

EXPOSE 80
```

I run 

    docker build -rm -t docker.crsinc.local/crsinc/dynenv-hipache .

Then I run 

    docker push docker.crsinc.local/crsinc/dynenv-hipache

With 0.6.7, it succeeds.  With 0.7.1, I get:

```
[debug] registry.go:436 [registry] Calling PUT http://docker.crsinc.local/v1/images/323ee02cbd5557b6598dab88bc3d3123863eb006dd4c34918b1a7c229b149439/layer
[debug] http.go:168 http://docker.crsinc.local/v1/images/323ee02cbd5557b6598dab88bc3d3123863eb006dd4c34918b1a7c229b149439/layer -- HEADERS: map[User-Agent:[docker/0.7.1 go/go1.1.2 git-commit/88df052 kernel/3.11.7 ]]
panic: runtime error: slice bounds out of range
 
goroutine 62 [running]:
archive/tar.(*Writer).writePAXHeader(0xc200298440, 0xc2007769c0, 0x55, 0xc200509ae0)
	/usr/lib/go/src/pkg/archive/tar/writer.go:233 +0x21d
```

(Full stack trace available here: https://gist.github.com/sdwr98/8005356)

This is 100% reproducible in my environment.  The docker private registry is the latest (0.6.1) version of stackbrew/registry fronted by nginx. 

UPDATE: this appears to be limited to CoreOS - Docker 0.7.1 seems to be working properly on an Ubuntu VM

**Comment by crawford** [comment]
<a href="https://github.com/philips"><img src="https://avatars.githubusercontent.com/u/33544?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philips](https://github.com/philips)**
_Monday Dec 30, 2013 at 23:12 GMT_

----

This is fixed in Docker 0.7.2 compiled with Go 1.2 which is in the latest CoreOS release: 176.0.0. Thanks!
